### ISSUE TITLE
Format objects in alternative way - additional option.

### ISSUE THREAD

**Issue by DawidaWina** [beautify-web/js-beautify#1049] opened 2016-10-27 12:51 UTC
# Description
> Hi! Could you add format objects in new alternative way as additional option?
> I think that a lot of people will want to format object in another way as is it shown in above example.
> As you can see, anotherObject values in new, alternate way will be format in one column.
> Spaces will be automatically added between keys and values to make that looks very easy-readable > code. Algorith to realise that is very easy, but effects will be amazing :)
> I hope to get answer. :)

# Input
The code before:
```
var anotherObject = {
    name:                         "name",
    surname: "surname",
    id:     "id"
};  
```

# Expected Output
The code should have looked like this after alternative beautification:
```
var anotherObject = {
    name:    "name",
    surname: "surname",
    id:      "id"
};
```

# Actual Output
The  code actually looked like this after beautification:
```
var anotherObject = {
    name: "name",
    surname: "surname",
    id: "id"
};  
```

# Steps to Reproduce
Iterate over keys and values in object and search the longest key. 
Range again over object and as many spaces after key, as excepted - result of equation:
(longest key length + white space) - (actual value length). Then show value.

## Environment
OS: Ubuntu

## New additional setting example
{
    alternative_object_format: true/false
}

**Comment by Oxicode** [comment] 2016-10-27 13:30
Why?

**Comment by DawidaWina** [comment] 2016-10-27 13:40
Oh. Now I can see that code in post has been destroyed. Please, check difference on following screenshot:
![jsbeautifier_issue](https://cloud.githubusercontent.com/assets/19266872/19769397/7c36cb42-9c5b-11e6-869c-b49d5411e8fa.png)

As you can first two objects, they are more readable than the 'default' one.
It is very helpful if there are bigger objects (more than 5 keys) with different lengths.

**Comment by bitwiseman** [comment] 2016-10-27 19:30
Duplicate of #365.

**Closed by bitwiseman** 2016-10-27 19:30 UTC
Labels: duplicate
