### ISSUE TITLE
The newest python jsbeautifier product wrong object with es6 "Lexical This" feature

### ISSUE THREAD

**Issue by cncolder** [beautify-web/js-beautify#818] opened 2015-11-25 05:46 UTC
a small snippet show this:

```javascript
{
  foo() {},
    bar() {}
}
```

**Comment by bitwiseman** [comment] 2015-11-25 21:58
Duplicate of #602.  Not obvious because of the title, but it is being worked on. :smile:

**Closed by bitwiseman** 2015-11-25 21:58 UTC
Labels: duplicate
