### ISSUE TITLE
Add check option to test if files are formatted correctly

### ISSUE THREAD

**Issue by Xenira** [beautify-web/js-beautify#1895] opened 2021-03-10 16:36 UTC
# Description
I need to verify if all files are formatted correctly in a git commit hook.
As the replace flag will be set to true when the input file string matches multiple files I propose to add a flag to only verify if everything is formatted correctly.

# Input
With this new feature, when I give like this input: 
```
js-beautyify --check -f src/**/*.html
```

# Expected Output
I'd like to see this output and exit code > 0:
```
[error] <file-path>
```

## Environment
OS: All

**Comment by bitwiseman** [comment] 2021-03-10 18:12
Duplicate of #741.

**Closed by bitwiseman** 2021-03-10 18:12 UTC
Labels: resolved: duplicate
