### ISSUE TITLE
Preserve columns

### ISSUE THREAD

**Issue by michaelalhilly** [beautify-web/js-beautify#1063] opened 2016-11-18 16:45 UTC
# Description
Is there a current configuration to preserve all inline tabs (columns)? If not would you consider this as a feature request. I find this style very readable and have seen it used widely.

NOTE: The code below may not render properly. The expected output should keep all equal signs aligned. This of course should be preserved without equal signs as well. So I guess it's a matter of preserving all inline tabs.

# Input
```
var AWS 			= require("aws-sdk");
var faker 			= require('faker');
var generate 			= require('./generate');
var test 			= false;
var items 			= 10;
var table_name 			= 'villagecity-user';
var key 			= 'email';
```

# Expected Output
```
var AWS 			= require("aws-sdk");
var faker 			= require('faker');
var generate 			= require('./generate');
var test 			= false;
var items 			= 10;
var table_name 			= 'villagecity-user';
var key 			= 'email';
```

# Actual Output
```
var AWS = require("aws-sdk");
var faker = require('faker');
var generate = require('./generate');
var test = false;
var items = 10;
var table_name = 'villagecity-user';
var key = 'email';
```

## Environment
OS:

## Settings
```json
{
    "indent_with_tabs": true,
    "preserve_newlines": true,
    "max_preserve_newlines": 4,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse-preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 4,
    "e4x": false
}
```

**Comment by bitwiseman** [comment] 2016-11-19 02:13
Duplicate of #603.  thanks!

**Closed by bitwiseman** 2016-11-19 02:13 UTC
Labels: duplicate

**Comment by michaelalhilly** [comment] 2016-11-19 02:21
Sorry! I searched the issues but missed that one. Thank you!
