### ISSUE TITLE
Installation fails for 1.7.0 on Windows/Linux/SmartOS

### ISSUE THREAD

**Issue by andrija-hers** [beautify-web/js-beautify#1252] opened 2017-09-18 10:22 UTC
Very easy to reproduce - just try to install it.
I tried on Windows, Linux and SmartOS and got the same thing.

npm install js-beautify
npm WARN enoent ENOENT: no such file or directory, open '/home/andra/trash/blah/package.json'
npm WARN blah No description
npm WARN blah No repository field.
npm WARN blah No README data
npm WARN blah No license field.
npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "js-beautify"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /home/andra/trash/blah/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/andra/trash/blah/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/andra/trash/blah/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andra/trash/blah/npm-debug.log

**Comment by nikolawan** [comment] 2017-09-18 10:31
#https://github.com/beautify-web/js-beautify/issues/1247

**Comment by achingbrain** [comment] 2017-09-18 10:41
I'm seeing this too.

**Comment by andreineculau** [comment] 2017-09-18 10:46
fwiw this is a dupe of https://github.com/beautify-web/js-beautify/issues/1247

**Comment by MRJBGO** [comment] 2017-09-18 13:19
Same for us. All jobs are failling ...

**Comment by chuhaienko** [comment] 2017-09-18 13:37
Previous version exists,
but last 1.7.0 - does not exists

yurii@hp0143:/home/si/$ npm i js-beautify@1.6.14
safedeals@1.0.0 /home/si/
└── js-beautify@1.6.14 

npm WARN si@1.0.0 No repository field.
yurii@hp0143:/home/si/$ npm i js-beautify@1.7.0
npm WARN si@1.0.0 No repository field.
npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "js-beautify@1.7.0"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /home/si/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/si/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/si/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/si/npm-debug.log

**Comment by shawninder** [comment] 2017-09-18 14:49
Same error here

**Comment by g1eny0ung** [comment] 2017-09-18 14:51
Same error for me...

**Comment by miguelb** [comment] 2017-09-18 15:43
same error here

**Comment by bitwiseman** [comment] 2017-09-18 16:31
Fixed in 1.7.2.

**Closed by bitwiseman** 2017-09-18 16:31 UTC
