### ISSUE TITLE
Beautify does not work with PHP and that is fine... but read this.

### ISSUE THREAD

**Issue by CodeAmend** [beautify-web/js-beautify#688] opened 2015-05-07 18:01 UTC
So Beautify does not support php. That is ok. 
So can you please not mess with code in php tags?

<b>What happens:</b> It scrunches all PHP code together and adds spaces after $ !!! 

<b>Way to fix it:</b> Just have Beautify NOT touch code in between the <?php ?> tags. 

I think this would solve a lot of my headache at least.

**Comment by bitwiseman** [comment] 2015-05-24 22:53
Please give an example input, actually output, and desired output.  
Also, where did your run this?  Was it on the web or from the command-line?  If command-line what command did you run?

**Comment by bitwiseman** [comment] 2015-05-27 23:48
@CodeAmend ?  I'd like to help you here. A little more info needed.

**Comment by T3charmy** [comment] 2015-06-03 16:42
@bitwiseman I can give you an example when I get home from work today, but generally what happens is: something like what this comment is: https://github.com/drewhamlett/brackets-beautify/issues/142#issuecomment-82316492

**Comment by CodeAmend** [comment] 2015-06-03 16:47
I recently switched 100% linux and I cannot get the same results as
windows. Let me work with it a bit more and see if I can prove what I am
talking about. Or better yet, its a non-issue now.

thank you.

**Comment by T3charmy** [comment] 2015-06-03 18:22
Well, regardless, I(plus a bunch of others) are still having this issue. it usually has to do with the $ becoming separated from the variable, or the extra space inside an array variable($example["one "])

**Comment by user501254** [comment] 2015-06-04 04:34
yes, one can just leave out the `<?php.....?>` portion but what if the document is long and it alternates between PHP and HTML; it would be a tedious task.

**Comment by T3charmy** [comment] 2015-06-04 13:18
@user501254 I'm for all optimizing the PHP code, in fact. it'd be really awesome if it could. Just as it sits right now, it will break most code you throw at it, which isn't really ideal. numerous times I've had to go back and correct files that have gotten messed up when beautifying, eventually I just stopped using it. I was spending more time correcting than it would have taken me to beautify it myself.

**Comment by bitwiseman** [comment] 2015-06-04 17:46
This is definitely a bug.  We shouldn't break things if we can avoid it.

**Comment by bitwiseman** [comment] 2015-06-04 17:59
This is a bug.  I'll fix shortly.

**Comment by T3charmy** [comment] 2015-06-04 18:32
another big thing this screws up, is since it puts all of the PHP on one line it would make something like:
```php
<?php
for($i = 1; $i <= 100; $i++;) {
    #count to 100!
    echo($i . "</br>");
}
?>
```
the beautify would cause that code to turn into
```php
<?php for($i=1 ; $i <=1 00; $i++;) { #count to 100! echo($i . "</br>"); } ?>
```

which due to the comment, everything after the # gets ignored, there for breaking scripts.

**Comment by CodeAmend** [comment] 2015-06-15 07:43
This is SO annoying it is making Beautify useless. Please just ignore all php code. PLEASE! I have to uninstall this, what could be amazing, extension.

I spent the last few days trying to figure out what was going on in my code!!! Turns out I had beautify on save turned on!!!

Just one small example of the HUNDREDS of problems it caused. 
before Beautify.
define('DB_PASSWORD', 'dbwjaMbK3TUNC4BP');

After Beautify
define('DB_PASSWORD ', 'dbwjaMbK3TUNC4BP ');

I never spotted it for 2 days! It costs me valuable working time. 

Unfortuantely, I am going to uninstall. If there is a way to give a low score, It is going to have to take a hit because of the php issues it is causing! 

Just ignore the php code!

**Comment by bitwiseman** [comment] 2015-06-16 02:33
Closing as duplicate of #490.  This is getting fixed under that issue.

**Closed by bitwiseman** 2015-06-16 02:33 UTC
Labels: bug

**Comment by freshdesignza** [comment] 2015-10-02 17:53
This just ruined thousands of lines of my code. Boooooo.

**Comment by Wendihihi** [comment] 2015-11-25 04:27
@freshdesignza You didn't make a backup huh?
