### ISSUE TITLE
Not indenting options argument to a function

### ISSUE THREAD

**Issue by zimmerboy** [beautify-web/js-beautify#1088] opened 2016-12-28 23:07 UTC
# Description

I looked through the open issues, but didn't see anything with a similar problem.

# Input
I have a function like this, which is using JQuery:

``` javascript
function createDiv(divId, divClass, divText) {

    const repoDiv = $('<div>', {
        id: divId,
        class: divClass
    })
    .append($('<h1>', {
        text: divText
    }));

    return repoDiv;
}
```

# Expected Output
It should look the same as the input, above.

# Actual Output
The  code actually looked like this after beautification.

The line `id: divId` has 12 spaces in front instead of the 8 I would have expected:

``` javascript
function createDiv(divId, divClass, divText) {

    const repoDiv = $('<div>', {
            id: divId,
            class: divClass
        })
        .append($('<h1>', {
            text: divText
        }));

    return repoDiv;
}
```

# Steps to Reproduce

## Environment
OS: Mac 

js-beautify 1.6.6

## Settings
Example:
```json
        "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],
        "brace_style": "collapse",
        "break_chained_methods": false,
        "e4x": false,
        "end_with_newline": false,
        "indent_char": " ",
        "indent_level": 0,
        "indent_size": 4,
        "indent_with_tabs": false,
        "jslint_happy": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "max_preserve_newlines": 5,
        "preserve_newlines": true,
        "space_after_anon_function": false,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false,
        "wrap_line_length": 0
```

**Comment by bitwiseman** [comment] 2016-12-29 05:46
This looks like a duplicate of #482.

**Closed** 2016-12-30 07:39 UTC
Labels: duplicate

**Comment by L5eoneill** [comment] 2019-04-04 13:02
What? Nothing at all like #482. This is basic indent level stuff, nothing about weird nesting or alternate indentations depending on ... whatever. This is just HTML that should have 2 space indenting, and js-beautify is ignoring the '2' setting and doing 4.
