### ISSUE TITLE
@decorators function broken after js-beautify, please help 

### ISSUE THREAD

**Issue by tsingson** [beautify-web/js-beautify#709] opened 2015-06-08 04:50 UTC
before:

```
@connectToStores([StarredReposByUserStore, UserStore, RepoStore], getState)
export default class UserPage {
  static propTypes = {
    // Injected by React Router:
    params: PropTypes.shape({
      login: PropTypes.string.isRequired
    }).isRequired,

    // Injected by @connectToStores:
    user: PropTypes.object,
    starred: PropTypes.arrayOf(PropTypes.object).isRequired,
    starredOwners: PropTypes.arrayOf(PropTypes.object).isRequired,
    isLoadingStarred: PropTypes.bool.isRequired,
    isLastPageOfStarred: PropTypes.bool.isRequired
  };

```

after prettify
```
@
connectToStores([StarredReposByUserStore, UserStore, RepoStore], getState)
export default class UserPage {
  static propTypes = {
    // Injected by React Router:
    params: PropTypes.shape({
      login: PropTypes.string.isRequired
    }).isRequired,

    // Injected by @connectToStores:
    user: PropTypes.object,
    starred: PropTypes.arrayOf(PropTypes.object).isRequired,
    starredOwners: PropTypes.arrayOf(PropTypes.object).isRequired,
    isLoadingStarred: PropTypes.bool.isRequired,
    isLastPageOfStarred: PropTypes.bool.isRequired
  };

```
@connectToStores   ----------it's a ES7 style  decorators,  it's prettify issue for me, would you please help me that how to fix this ?

would some one tell me how to hack or fix this in js-beautify source code ??

thanks a lot

**Comment by bitwiseman** [comment] 2015-06-08 23:37
Duplicate of #685.

**Closed** 2015-06-08 23:38 UTC
Labels: duplicate
