### ISSUE TITLE
space in media queries after colon &: selectors

### ISSUE THREAD

**Issue by jarnovanrhijn** [beautify-web/js-beautify#565] opened 2014-10-22 08:06 UTC
Hi,

First of all, great plugin and thanks for the active updates!

I've read several other issues that might be related to this one but i couldn't find to be the same.

If, in CSS you have add a media query and you put an &: selector right after the media query, it still adds a space where it shoudn't. if you move the selector beneath an other selector it doesn't add a space.

for example:

     @media(min-width:768px) {
          .selector::after {
               <-- property : value -->
          }
         .other-selector {
               <-- property : value -->
          }
     }

This would add a space to the ::after selector

however if you swap the to selectors it would not add a space.

for example:

     @media(min-width:768px) {
          .other-selector {
               <-- property : value -->
          }
          .selector::after {
               <-- property : value -->
          }
     }
would result in not adding spaces.

Thanks and great work!

**Comment by bitwiseman** [comment] 2016-01-29 19:34
It looks like this is fixed in 1.6.0.  Need to add a regression test.

**Closed** 2016-08-30 01:29 UTC
Labels: beautify-css, bug
