### ISSUE TITLE
ternary operations

### ISSUE THREAD

**Issue by cybermerlin** [beautify-web/js-beautify#670] opened 2015-04-16 15:34 UTC
beautify format for ternary operations if line length more to wrap_line_length
```
var some = question
    ? value1
    : value2;
```

**Comment by alexjamesbrown** [comment] 2015-06-24 23:20
+1

**Comment by alexjamesbrown** [comment] 2015-06-24 23:20
although possible duplicate of #605

**Comment by olsonpm** [comment] 2015-07-01 15:17
If either of you are interested, bitwiseman and I are discussing implementation on [this thread](https://github.com/beautify-web/js-beautify/pull/611#issuecomment-116768891).  Please join in if you have any input.

I only raise this because what began as 'ternary operations' newline placement is broadening out to all operators.  Right now we're hashing out which operators possibly belong on a newline.

**Comment by bitwiseman** [comment] 2016-02-03 19:32
#735 added option to control this.

**Closed by bitwiseman** 2016-02-03 19:32 UTC
Labels: enhancement

**Comment by alexjamesbrown** [comment] 2016-02-03 20:07
cool! thanks
