### ISSUE TITLE
Javascript ++ Operator get wrong indent

### ISSUE THREAD

**Issue by kerraway** [beautify-web/js-beautify#1283] opened 2017-10-29 14:24 UTC
# Description
> When I use ++, the next line get wrong indent. If I use += 1, or end with ; , the next line is ok.

# Input
The code looked like this before beautification:
<img width="308" alt="before" src="https://user-images.githubusercontent.com/5738688/32144677-72b5da6e-bcf7-11e7-9702-db6f6979eec1.png">

# Actual Output
The  code actually looked like this after beautification:
<img width="332" alt="after" src="https://user-images.githubusercontent.com/5738688/32144678-7b6f68c8-bcf7-11e7-869d-e1e15dcadb4d.png">

## Environment
OS:
macOS 10.13

## Settings
Example:
```json
"js": {
    "brace_style": "collapse-preserve-inline",
    "break_chained_methods": false,
    "comma_first": false,
    "e4x": false,
    "jslint_happy": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "operator_position": "before-newline",
    "space_after_anon_function": false,
    "space_before_conditional": true,
    "space_in_empty_paren": false,
    "space_in_paren": false,
    "unescape_strings": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2
  }
```

**Comment by bitwiseman** [comment] 2017-10-30 06:13
Duplicate of #203.

**Comment by Gegoiuty** [comment] 2017-10-30 09:42
Thand U.

A little incomprehension: what should I do with this issue?

I mean, this is a old issue since 2013, but it still exists. So, Should I change "window.store.loading++" to "window.store.loading++;" or "++window.store.loading"?

When I change "window.store.loading--" to "--window.store.loading", I get this:
![1509356408973](https://user-images.githubusercontent.com/5738688/32164177-a103546c-bd99-11e7-88d2-f9d3d34fbdaf.jpg)

**Comment by bitwiseman** [comment] 2017-10-30 18:57
@Gegoiuty 

Actually: this doesn't happen on http://jsbeautifier.org/ .  Please try you code there.  If it works (formats correctly), then your editor/plugin needs updating to use the latest js-beautifier.

**Comment by Gegoiuty** [comment] 2017-10-31 03:52
I try code in http://jsbeautifier.org/ , and it doesn't format correctly.

![1509421866160](https://user-images.githubusercontent.com/5738688/32206734-e600c390-be31-11e7-9909-9fb083c120c5.jpg)

And this is my code.
```
import Vue from 'vue'
import axios from 'axios'
import Qs from 'qs'
import moment from 'moment'
import api from 'src/common/api'
import _ from 'lodash'
import Cookies from 'js-cookie'
import router from '../router/index'
import {
    SELECTED_PRODUCT,
    LOGIN_STRING
} from './constant'
import {
    Notification,
    Loading,
    MessageBox
} from 'element-ui'

window.Vue = Vue
window._ = _
window.moment = moment
window.axios = axios
window.Cookies = Cookies
window.app = window.app || {}
window.store = {
    loading: 0
}

Object.assign(app, {
    api,
})

axios.defaults.transformRequest = [(data) => Qs.stringify(data)]
axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded'
axios.defaults.headers.put['Content-Type'] = 'application/x-www-form-urlencoded'

axios.interceptors.request.use(
    config => {
        // loading
        window.store.loading++

            let extraParams = {}
        if (!config.params || !config.params.product) {
            const product = Cookies.get(SELECTED_PRODUCT) ? Cookies.get(SELECTED_PRODUCT) : null
            extraParams.product = product
        }
        const login_string = Cookies.get(LOGIN_STRING)
        if (login_string) {
            extraParams.login_string = login_string
        }
        const params = config.params || {}
        config.params = Object.assign(params, extraParams)
        return config
    },
    error => {
        return Promise.reject(error)
    }
)

let alerted = false

axios.interceptors.response.use(
    res => {
        window.store.loading--;
        if (res.data && res.data.code === 0) {
            return res.data.data
        }
        Notification.error({
            title: 'Fail',
            message: res.data.msg
        })
        return Promise.reject(res.data.msg)
    },
    error => {
        const err = error.response
        window.store.loading--

            if (err) {
                switch (err.status) {

                    case 401:
                        if (!alerted) {
                            alerted = true
                            MessageBox.alert('Please login again.', 'Logout!', {
                                confirmButtonText: 'confirm',
                                callback() {
                                    Cookies.remove(LOGIN_STRING)
                                    router.push({
                                        path: '/login',
                                        query: {
                                            redirectUrl: window.location.href
                                        }
                                    })
                                }
                            })
                        }
                        break
                    default:
                        Notification.error({
                            title: 'Fail',
                            message: err
                        })
                        return Promise.reject(error)
                }
            }
        return Promise.reject(error)
    }
)
```

**Comment by Gegoiuty** [comment] 2017-10-31 03:54
By the way, I use HTML-CSS-JS Prettify in Sublime Text 3 Build 3143, macOS 10.13.

**Comment by bitwiseman** [comment] 2017-11-01 00:26
@Gegoiuty 
Interesting.  Here's the minimal repro:


js
```
// happens
use(
  config => {
    window.store.loading++

      let extraParams = {}
  }
)

// does not happen.
use(
  config => {
    // loading
    loading++

    let extraParams = {}
  }
)
```

**Comment by Elrendio** [comment] 2018-05-02 13:08
Hello, do you have any info on when and if you will adresse this issue ?

If I want to help can I propose a PR, if yes what are your code standards ?

**Comment by Elrendio** [comment] 2018-05-04 13:41
Hello, I'v done a commit to resolve this issue (handled python and node changes), all the test pass (python and js). However I dont have the rights to push a new branch and create à PR.

**Comment by bitwiseman** [comment] 2018-05-04 21:48
Thanks!
Create a fork, push to a branch there, and PR from there.

**Closed** 2018-06-29 23:20 UTC
Labels: good first issue, language: javascript, type: bug
