### ISSUE TITLE
Nested ERB blocks

### ISSUE THREAD

**Issue by hkalexling** [beautify-web/js-beautify#1804] opened 2020-06-17 16:14 UTC
# Description

The HTML beautifier doesn't indent nested ERB blocks correctly. 

# Input
The code looked like this before beautification:
```erb
<% if item.is_a? Title %>
<% if grouped_count == 1 %>
<p><%= item.size %> entries</p>
<% else %>
<p><%= grouped_count %> new entries</p>
<% end %>
<% end %>
```

# Expected Output
The code should have looked like this after beautification:
```erb
<% if item.is_a? Title %>
  <% if grouped_count == 1 %>
    <p><%= item.size %> entries</p>
  <% else %>
    <p><%= grouped_count %> new entries</p>
  <% end %>
<% end %>
```

# Actual Output
The  code actually looked like this after beautification (unchanged):
```erb
<% if item.is_a? Title %>
<% if grouped_count == 1 %>
<p><%= item.size %> entries</p>
<% else %>
<p><%= grouped_count %> new entries</p>
<% end %>
<% end %>
```

## Environment
OS: Ubuntu 18.04

## Settings
I ran `html-beautify` version 1.11.0 with `html-beautify --templating=erb test.ecr`

**Comment by bitwiseman** [comment] 2020-06-18 20:22
Duplicate of #1363.

**Closed by bitwiseman** 2020-06-18 20:22 UTC
Labels: resolved: duplicate
