### ISSUE TITLE
CSS first-child pseudo child selector incorrectly merged with parent selector

### ISSUE THREAD

**Issue by prettydiff** [beautify-web/js-beautify#1006] opened 2016-08-27 16:15 UTC
https://github.com/Glavin001/atom-beautify/issues/1158

**Comment by bitwiseman** [comment] 2016-08-27 20:46
Duplicate of #985

**Comment by bitwiseman** [comment] 2016-08-31 20:10
Duplicate of #985

**Closed by bitwiseman** 2016-08-31 20:10 UTC
Labels: duplicate
