### ISSUE TITLE
Beautify removes Array

### ISSUE THREAD

**Issue by jhhcs** [beautify-web/js-beautify#1898] opened 2021-03-25 22:39 UTC
# Description
I noticed that in this one particular instance, an array definition was stripped from the code by js-beautify.

# Input
The code looked like this before beautification:
```
var _0xb050 = ['foo', 'bar', 'baz'];
(function(_0x4f7b12, _0x1ae29e) {}(_0xb050, 0x6c));
```

# Expected Output
The code should have looked like this after beautification:
```
var _0xb050 = ['foo', 'bar', 'baz'];
(function(_0x4f7b12, _0x1ae29e) {}(_0xb050, 0x6c));
```

# Actual Output
The  code actually looked like this after beautification:
```
(function(_0x4f7b12, _0x1ae29e) {}(_0xb050, 0x6c));
```

# Steps to Reproduce
This can be checked in the [web interface](https://beautifier.io).

**Comment by bitwiseman** [comment] 2021-03-29 14:46
Duplicate of #1350

**Closed by bitwiseman** 2021-03-29 14:46 UTC
Labels: resolved: duplicate
