### ISSUE TITLE
Keep adding new lines between comments in css

### ISSUE THREAD

**Issue by zyyedi** [beautify-web/js-beautify#1220] opened 2017-07-23 10:01 UTC
Hi, I just download the plugin for sublime text, and I met some problems. It keeps adding new lines after each reformatting.
<img width="535" alt="screen shot 2017-07-23 at 5 53 54 pm" src="https://user-images.githubusercontent.com/26909419/28498472-de8b67fa-6fd0-11e7-9b85-b28ca549334f.png">
<img width="598" alt="screen shot 2017-07-23 at 5 54 13 pm" src="https://user-images.githubusercontent.com/26909419/28498473-df8e4f46-6fd0-11e7-9646-5f7297a1ce33.png">
<img width="576" alt="screen shot 2017-07-23 at 5 54 22 pm" src="https://user-images.githubusercontent.com/26909419/28498474-e0db5f92-6fd0-11e7-97f9-739315fff55d.png">

**Comment by bitwiseman** [comment] 2017-07-25 19:53
Duplicate of #1185.

**Closed by bitwiseman** 2017-07-25 19:53 UTC
