### ISSUE TITLE
collapse-preserve-inline and throw

### ISSUE THREAD

**Issue by ainthek** [beautify-web/js-beautify#962] opened 2016-07-03 09:14 UTC
I'm using js-beautify 1.6.3 on OSX for CLI formatting, main reason, to be cosnsitent with editor formatting (Sublime).
I have noticed that there is difference even if using same settings.
After digging deeper I have found theta runnting js-beautyfy twice from CLI, will give me what I expect.
Digging deeper 'throws' seems to cause trouble

	
	echo 'if (a == 1) { a++; }' | js-beautify -b collapse-preserve-inline

prints expected
	
	if (a == 1) { a++; }

however 

	echo 'if (a == 1) { throw "aaa" }' | js-beautify -b collapse-preserve-inline

prints unexpected (nor collapsed nor expanded version)

	if (a == 1) {
    	throw "aaa" }

why ?

and now the funny part (double formatting):

	echo 'if (a == 1) { throw "aaa" }' | js-beautify -b collapse-preserve-inline | js-beautify -b collapse-preserve-inline 

prints:

	if (a == 1) {
    	throw "aaa"
	}

so it is unstable and formatting result depends on how many times you run formatter ?

Thanx for help

**Comment by bitwiseman** [comment] 2016-07-13 23:31
Hello, excellent bug report and details.  I've added this to the next milestone.

**Comment by bitwiseman** [comment] 2016-08-07 22:39
Duplicate of #898

**Closed** 2016-08-08 02:24 UTC
Labels: duplicate
