### ISSUE TITLE
Comments in a non-semicolon style are incorrectly indented

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1071] opened 2016-12-10 15:12 UTC
Code:
```
var a = 1
// this is a comment
```
This gets beautified to
```
var a = 1
    // this is a comment
```
because of a missing semi-colon in the first line.

**Comment by bitwiseman** [comment] 2016-12-22 07:46
Duplicate of #815

**Closed by bitwiseman** 2016-12-22 07:46 UTC
