### ISSUE TITLE
space_after_named_function not working inside an ES6 class

### ISSUE THREAD

**Issue by jacobrec** [beautify-web/js-beautify#1622] opened 2019-01-28 19:33 UTC
# Description
space_after_named_function not working inside an ES6 class. I don't know if this is the indented behaviour or not, but it was not what I was expecting

# Input
The code looked like this before beautification:
```
class blah {
  constructor() {
    this.doStuff()
  }

  doStuff() {
    console.log("stuff")
  }
}

function test() {}
```

# Expected Output
The code should have looked like this after beautification:
```
class blah {
  constructor () {
    this.doStuff()
  }

  doStuff () {
    console.log("stuff")
  }
}

function test () {}
```

# Actual Output
The  code actually looked like this after beautification:
```
class blah {
  constructor() {
    this.doStuff()
  }

  doStuff() {
    console.log("stuff")
  }
}

function test () {}
```

# Steps to Reproduce
Run on https://beautifier.io/

## Environment
https://beautifier.io/
Also, ubuntu 18.10

## Settings
Example:
```json
{
  "indent_size": "2",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": true,
  "space_after_anon_function": true,
  "space_after_named_function": true
}
```

**Comment by Favna** [comment] 2019-02-27 10:18
I can second this as I noticed it as well and (wrongfully) reported it on HookyQR's VSCode Beautify which apparently uses js-beautify in the background.

This was my code snippet from the issue there, which is just another bit of code that can be used for reproduction.

Full code as well as expected result:

```ts
export default class StringArrayType extends ArgumentType {
    constructor (client) {
        super(client, 'stringarray');
    }
}
```

Actual result:

```ts
export default class StringArrayType extends ArgumentType {
    constructor(client) {
        super(client, 'stringarray');
    }
}
```

**Comment by bitwiseman** [comment] 2019-02-27 22:43
This should be pretty simple but it will need to differentiate from:
```
function test() {
    constructor();
}
```

**Comment by mhnaeem** [comment] 2022-04-11 06:08
Added a new PR for this feature

**Comment by aichingm** [comment] 2022-06-11 21:42
From what I can tell this should already have landed in 1.14.3 right? 

If so it does not seam to be working.

JS test:

```
$ echo "class A {bar(){}}function foo(){}" | node node_modules/.bin/js-beautify --space-after-named-function  -

class A {
    bar() {}
}

function foo () {}
```

Python test:
```
$ echo "class A {bar(){}}function foo(){}" | js-beautify --space-after-named-function  -

class A {
    bar() {}
}

function foo () {}
```

Versions:

```
$ js-beautify -h
jsbeautifier.py@1.14.3
...
```

```
$ node node_modules/.bin/js-beautify -h
js-beautify@1.14.3
...
```

**Comment by bitwiseman** [comment] 2022-06-20 17:31
Yup, not fixed.

**Closed** 2022-06-20 21:33 UTC
Labels: type: bug, language: ecma-2015

**Comment by bitwiseman** [comment] 2022-06-20 23:58
Turns out this was in the 1.14.4 - released today.
