### ISSUE TITLE
pip install cssbeautifier fails

### ISSUE THREAD

**Issue by tysmith** [beautify-web/js-beautify#1808] opened 2020-06-29 17:43 UTC
Pip installing cssbeautifier fails with the following message:
```
$ python3 -m pip install cssbeautifier --user
Collecting cssbeautifier
  Downloading cssbeautifier-1.11.0.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ud0acpi6
         cwd: /tmp/pip-install-9m8ry79r/cssbeautifier/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py", line 7, in <module>
        from jsbeautifier.__version__ import __version__
    ModuleNotFoundError: No module named 'jsbeautifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It does not seem to matter if jsbeautifier is installed or not. I believe this is a packaging issue because if I git clone the repo and run `python3 -m pip install -e python/` both cssbeautifier and jsbeautifier are installed successfully (and work great!).

Side note: That led me to wonder if I could install both cssbeautifier and jsbeautifier by running `python3 -m pip install jsbeautifier`. So I tried and only jsbeautifier is installed (as expected).

**Comment by returntrip** [comment] 2020-08-17 19:56
Should this be fixed in 1.12.0?

```
python3 -m pip install cssbeautifier --user
Collecting cssbeautifier
  Using cached https://files.pythonhosted.org/packages/11/01/7bc6c46af8c2281541a4d8adab4648c3c8356e2729418705eb03129a971d/cssbeautifier-1.12.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphdcd99p2
       cwd: /tmp/pip-install-05i411z9/cssbeautifier
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-z4vzjdzx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-z4vzjdzx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-z4vzjdzx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 266, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-z4vzjdzx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 7, in <module>
      from jsbeautifier.__version__ import __version__
  ModuleNotFoundError: No module named 'jsbeautifier'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphdcd99p2 Check the logs for full command output.
```

**Comment by bitwiseman** [comment] 2020-08-17 21:12
@returntrip 
Yes, I was expecting it to be fixed...

**Comment by bitwiseman** [comment] 2020-08-17 21:32
@thp 
Was this a mistake on my part when creating release?

**Comment by bitwiseman** [comment] 2020-08-18 15:28
The problem is if any _`_init__.py` in `cssbeautifier` contains reference to `jsbeautifier` we get this failure.

**Closed** 2020-08-19 20:39 UTC
Labels: implementation: python, type: bug
