### ISSUE TITLE
wrap_attributes HTML does not respect indentation

### ISSUE THREAD

**Issue by ooade** [beautify-web/js-beautify#1300] opened 2017-12-05 10:43 UTC
# Description

# Input
The code looked like this before beautification:
```
<form @submit.prevent="submitForm" name="signup">
```

# Expected Output
The code should have looked like this after beautification:
I expected it to respect my indentation i.e tabs before `@submit...` but it changes to spaces as the actual output below
```
<form
->@submit.prevent="submitForm"
->name="signup"
>
```

# Actual Output
The  code actually looked like this after beautification:
```
<form
 @submit.prevent="submitForm"
 name="signup"
>
```

# Steps to Reproduce
No steps to Introduce just format and that shows up.

## Environment
OS: Ubuntu 17.10

## Settings
Example:
```json
{
    "indent_with_tabs": true,
    "wrap_attributes": "force-expand-multiline"
}
```

**Comment by bitwiseman** [comment] 2017-12-06 20:06
Duplicate of #1294.  Thanks!

**Closed by bitwiseman** 2017-12-06 20:06 UTC
Labels: resolved: duplicate
