### ISSUE TITLE
String breakline for # String

### ISSUE THREAD

**Issue by halallahh** [beautify-web/js-beautify#1061] opened 2016-11-16 21:21 UTC
How can I prevent breakline for hashtag with string? (eg: # pen apple)

# Input
The code looked like this before beautification:
```
# string
```

# Expected Output
The code should have looked like this after beautification:
```
# string
```

# Actual Output
The  code actually looked like this after beautification:
```
#
string
```

**Comment by bitwiseman** [comment] 2016-11-17 15:40
Which language?  What is the code around this?

**Comment by halallahh** [comment] 2016-11-18 10:23
Javascript. code Template literals like this:

```javascript
const demo = `
# demo
# demo1
`;
```

**Comment by bitwiseman** [comment] 2016-12-22 07:49
I cannot reproduce this  issue on http://jsbeautifier.org/.  Closing.

**Closed by bitwiseman** 2016-12-22 07:49 UTC
