### ISSUE TITLE
Extra space added in html attributes

### ISSUE THREAD

**Issue by mohanraj0411** [beautify-web/js-beautify#976] opened 2016-07-21 17:40 UTC
Extra space added in html attributes which stops execution of boostrap toggle button

**Given HTML:**

`<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">`

**beautifier produces:**

`<button type="button " class="navbar-toggle " data-toggle="collapse " data-target="#navbar " aria-expanded="true " aria-controls="navbar ">`

this space is stop execution of boostrap toggle navbar button in mobile.

from **class="navbar-toggle"** to **class="navbar-toggle "**

**Comment by bitwiseman** [comment] 2016-07-22 01:05
What command are you running to get this result?

**Comment by mohanraj0411** [comment] 2016-07-25 05:56
After enable automatically format when a file is saved.

**Comment by afogas** [comment] 2016-07-28 06:38
+1

**Comment by afogas** [comment] 2016-07-28 06:38
I face the same issue. it is quite annoying....

**Comment by ahtecharrow** [comment] 2016-07-28 06:39
The same behavior for me.

**Comment by mohanraj0411** [comment] 2016-08-07 09:59
I have found source of the problem, but I did no how to fix it. Please help.

when I run html file on server that extra space is add. It not happen in local dir files.

**Comment by bitwiseman** [comment] 2016-08-08 01:49
@mohanraj0411, @ahtecharrow @afogas 
I cannot reproduce this error, please provide the full file that you are beautifying and what you are doing to beautify this.

**Comment by bitwiseman** [comment] 2016-12-26 21:09
@mohanraj0411, @ahtecharrow @afogas 
I'm closing this for now.  Please comment and I will reopen.

**Closed by bitwiseman** 2016-12-26 21:09 UTC
Labels: needs more info

**Comment by re6exp** [comment] 2017-02-17 15:12
Before:
    <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
After:
< div class = "qq-uploader-selector qq-uploader" qq - drop - area - text = "Drop files here" >

**Comment by bitwiseman** [comment] 2017-02-17 22:39
@re6exp 
what are you using to get this result? Does it repo on http://jsbeautifier.org/ ?

**Comment by re6exp** [comment] 2017-02-18 11:58
I'm using Atom.io with [atom-beautify](https://github.com/Glavin001/atom-beautify) package, which uses js-beautify under the hood.

I've tried link you provided, it works like a charm!

I'll try to find the cause in that package or in the settings of the package. Thank you very much!

**Comment by bitwiseman** [comment] 2017-02-19 02:33
What is the full file?  Is it a javascript file?  Or an html file?

**Comment by re6exp** [comment] 2017-02-19 06:48
The full file was an HTML fragment.

I'm sorry to trouble you, now it works. I change atom-beautify code where options of js-beautify are been used, and now everything works perfectly. So, there is nothing to do with js-beautify.

Anyway, thank you for your participation!

**Comment by bitwiseman** [comment] 2017-02-19 08:14
@re6exp Glad to help!
