### ISSUE TITLE
Add option to indent HTML template blocks

### ISSUE THREAD

**Issue by jkevingutierrez** [beautify-web/js-beautify#1828] opened 2020-08-06 19:25 UTC
# Description
Using Django template (I guess it could be needed for any other template) it would be good to be able to indent `if` and `for` blocks:

`{% if %}{% endif %}`
`{% for %}{% endfor %}`

It would be great to have an option to control the indentation of these blocks.

# Input
With this new feature, when I give like this input: 
```html
<main id="page-content" class="main">
  {% if True %}
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  {% endif %}
</main>

```

# Expected Output
I'd like to see this output:
```html
<main id="page-content" class="main">
  {% if True %}
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  {% endif %}
</main>

```

**Comment by bitwiseman** [comment] 2020-08-08 00:11
Duplicate of #477

**Closed by bitwiseman** 2020-08-08 00:11 UTC
Labels: resolved: duplicate
