### ISSUE TITLE
HTML - preserve inline attributes

### ISSUE THREAD

**Issue by IgorNovozhilov** [beautify-web/js-beautify#1295] opened 2017-11-22 14:06 UTC
Is it possible to make so that `html-beautify`, kept the spaces and new-line attributes specified in one line, by analogy with `preserve-inline`. While maintaining aligning the indents on the attributes of a new row by analogy with `force-aligned`?
> PS: Need for HTML templates

# Input
The code looked like this before beautification:
```html
<div>
   <tmpl:CONTROLS.Items name="my_name"
      class="Items"
      id="id_1"
      itemsDragNDrop="{{ true }}"
      itemsActions="{{ ['copy'] }}"
      anyOpt1="1"
      anyOpt2="2"
      anyOpt3="3"
      anyOpt4="4">
         <tmpl:Array>
            <tmpl:Object id="1"    title="Title 1"    width="90px" />
            <tmpl:Object id="12"   title="Title 12"   width="100px" />
            <tmpl:Object id="123"  title="Title 123"  width="120px" />
            <tmpl:Object id="1234" title="Title 1234" width="150px" />
         </tmpl:Array>
   </tmpl:CONTROLS.Items>
</div>
```

# Expected Output
The code should have looked like this after beautification:
```html
<div>
   <tmpl:CONTROLS.Items name="my_name"
                        class="Items"
                        id="id_1"
                        itemsDragNDrop="{{ true }}"
                        itemsActions="{{ ['copy'] }}"
                        anyOpt1="1"
                        anyOpt2="2"
                        anyOpt3="3"
                        anyOpt4="4">
         <tmpl:Array>
            <tmpl:Object id="1"    title="Title 1"    width="90px" />
            <tmpl:Object id="12"   title="Title 12"   width="100px" />
            <tmpl:Object id="123"  title="Title 123"  width="120px" />
            <tmpl:Object id="1234" title="Title 1234" width="150px" />
         </tmpl:Array>
   </tmpl:CONTROLS.Items>
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```html
<div>
   <tmpl:CONTROLS.Items name="my_name"
                        class="Items"
                        id="id_1"
                        itemsDragNDrop="{{ true }}"
                        itemsActions="{{ ['copy'] }}"
                        anyOpt1="1"
                        anyOpt2="2"
                        anyOpt3="3"
                        anyOpt4="4">
      <tmpl:Array>
         <tmpl:Object id="1"
                      title="Title 1"
                      width="90px" />
         <tmpl:Object id="12"
                      title="Title 12"
                      width="100px" />
         <tmpl:Object id="123"
                      title="Title 123"
                      width="120px" />
         <tmpl:Object id="1234"
                      title="Title 1234"
                      width="150px" />
      </tmpl:Array>
   </tmpl:CONTROLS.Items>
</div>
```

# Steps to Reproduce
1. do beatify `Input code block`

## Environment
OS: win7-pro

## Settings
Example:
```json
{
   "indent_size": 3,
   "brace_style": "collapse,preserve-inline",
   "html": {
      "wrap_attributes": "force-aligned"
   }
}
```

**Comment by bitwiseman** [comment] 2017-11-27 21:46
@IgorNovozhilov It sounds like what you want is an "aligned" setting (without force).

**Comment by IgorNovozhilov** [comment] 2017-11-28 11:41
@bitwiseman, yes

**Comment by bitwiseman** [comment] 2017-11-28 20:04
Cool, this is a duplicate of #1262.

**Closed** 2017-11-28 20:05 UTC
Labels: resolved: duplicate

**Comment by IgorNovozhilov** [comment] 2018-10-10 21:02
это https://github.com/beautify-web/js-beautify/pull/1571 подойдет :)
