### ISSUE TITLE
HTML option for automatic insertion of new lines before closing tag, when new line is inserted after opening tag

### ISSUE THREAD

**Issue by youlam** [beautify-web/js-beautify#1803] opened 2020-06-08 16:20 UTC
Currently, if one inserts a new line after `<p>` in this input...
```
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis fugiat sunt, beatae repellat maiores quidem. Velit laboriosam at in repudiandae ex non, rerum accusamus sed explicabo minus, reprehenderit cumque aliquid magnam ipsam sapiente error dolores obcaecati ratione placeat?</p>
```

...one obtains this output...

```
<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis fugiat sunt, beatae repellat maiores quidem. Velit laboriosam at in repudiandae ex non, rerum accusamus sed explicabo minus, reprehenderit cumque aliquid magnam ipsam sapiente error dolores obcaecati ratione placeat?</p>
```

...which is impractical because the intent will almost always be to insert a new line before `</p>` as well, i.e., it would be more practical to for a new line to automatically be inserted before `</p>` and obtain this output automatically:
```
<p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis fugiat sunt, beatae repellat maiores quidem. Velit laboriosam at in repudiandae ex non, rerum accusamus sed explicabo minus, reprehenderit cumque aliquid magnam ipsam sapiente error dolores obcaecati ratione placeat?
</p>
```

There are edge cases when this behavior is not desirable, but hardly ever with the `<p>` element, and it would be nice anyway to be able to request this behavior as an option?

Working on: VSCode.

**Comment by bitwiseman** [comment] 2020-06-11 21:13
Duplicate of #1468.
Thanks!

**Closed by bitwiseman** 2020-06-11 21:13 UTC
Labels: language: html, resolved: duplicate
