### ISSUE TITLE
FR: Support for space-after-named-function

### ISSUE THREAD

**Issue by rclai** [beautify-web/js-beautify#707] opened 2015-06-06 22:14 UTC
This should work just like `space-after-anon-function`, but for named function expressions:

``` js
var myFunction = function someName () {};
                                  ^
```

**Comment by bitwiseman** [comment] 2015-06-08 16:35
Do you mean:
```
var myFunction = function  someName () {};
```

**Comment by rclai** [comment] 2015-06-08 16:54
Oh yeah, whoops, edited.

**Comment by laggingreflex** [comment] 2016-09-25 18:27
Related/dupe: #608

**Comment by kanedauy** [comment] 2017-02-15 11:39
Yes, I want this, I try to use standard and is bothering me with this all the time.

**Comment by mesqueeb** [comment] 2018-03-05 15:55
I am also trying to recreate the Standard ruleset: https://github.com/beautify-web/js-beautify/issues/1356
Any chance you guys can share your config file how you've recreated the Standard ruleset?

**Comment by MacKLess** [comment] 2018-09-26 20:07
Closed as a duplicate of #608

**Closed by MacKLess** 2018-09-26 20:07 UTC
Labels: type: enhancement
