### ISSUE TITLE
Wrongly indented object argument of method after add chained method

### ISSUE THREAD

**Issue by mytharcher** [beautify-web/js-beautify#1673] opened 2019-05-22 04:28 UTC
# Description

As example below.

# Input
The code looked like this before beautification:
```
a({
  a: 1
});

a({
  a: 1
})
  .then();
```

# Expected Output
The code should have looked like this after beautification:
```
a({
  a: 1
});

a({
  a: 1
})
  .then();
```

# Actual Output
The  code actually looked like this after beautification:
```
a({
  a: 1
});

a({
    a: 1 // should be 2 spaces
  }) // should be 0 space
  .then();
```

# Steps to Reproduce

1. A function call;
2. A function call with an object argument;
3. Add a chained function call;

## Environment

<https://beautifier.io/> on Chrome 74 of macOS 10.14.4

## Settings

```json
{
  "indent_size": "2",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": true,
  "break_chained_methods": false,
  "indent_scripts": "keep",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false,
  "unindent_chained_methods": false
}
```

**Comment by bitwiseman** [comment] 2019-05-22 17:11
Duplicate of #1651. 
Please feel free to weigh in or help out there.

**Closed** 2019-05-22 17:11 UTC
Labels: resolved: duplicate
