### ISSUE TITLE
Space in braces

### ISSUE THREAD

**Issue by i5ar** [beautify-web/js-beautify#1630] opened 2019-02-10 13:28 UTC
Add option `space_in_braces` so

```
window.history.pushState({ html: response.html, pageTitle: response.pageTitle }, "", urlPath);
```
can format to
```
window.history.pushState({html: response.html, pageTitle: response.pageTitle}, "", urlPath);
``` 
For instance, Visual Studio Code uses the option `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false`.

Thank you.

**Comment by bitwiseman** [comment] 2019-02-11 17:01
Duplicate of #1204

**Closed** 2019-02-11 17:01 UTC
Labels: resolved: duplicate, type: enhancement
