### ISSUE TITLE
Wrong code formatting using Handlebars

### ISSUE THREAD

**Issue by boustanihani** [beautify-web/js-beautify#576] opened 2014-11-12 17:28 UTC
Is there any reason for disabling the formatting of `'a', 'span', 'img', 'strong',...` ???
https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L115

**Comment by bitwiseman** [comment] 2015-01-29 19:45
Thanks for the info.

**Comment by boustanihani** [comment] 2015-02-11 11:43
@bitwiseman is there any special reason for leaving the following tags unformatted =>
https://github.com/beautify-web/js-beautify/blob/v1.5.4/js/lib/beautify-html.js#L115
```unformatted = options.unformatted || ['a', 'span', 'img', 'bdo', 'em', 'strong', 'dfn', 'code', 'samp', 'kbd', 'var', 'cite', 'abbr', 'acronym', 'q', 'sub', 'sup', 'tt', 'i', 'b', 'big', 'small', 'u', 's', 'strike', 'font', 'ins', 'del', 'pre', 'address', 'dt', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'];```

**Comment by bitwiseman** [comment] 2015-02-11 19:48
In this case "unformatted" means, not put on a new line and not reindented.  This makes sense as these tags can occur like `<span><div><a href="b.html">E</a>xample where the spacing around the tags</div> matters.</span>`  If we reformatted these, we'd end up adding unintended whitespace to the output.

**Comment by boustanihani** [comment] 2015-02-11 20:46
I would agree if we were talking about pure **HTML** but in Handlebars you have sometimes **if-blocks inside span** for example:
```html
<div>
    <small>SMALL TEXT</small>
    <span>
        {{#if isOwner}}
            <span><i class="fa fa-close"></i></span>
        {{else}}
            <span><i class="fa fa-bolt"></i></span>
        {{/if}}
    </span>
    <strong>{{userName}}:&nbsp;</strong>{{text}}
</div>
```
I formatted the previous code manually, but if I let beautify do it form me the code will look like:
```html
<div>
    <small>SMALL TEXT</small>
    <span>
        {{#if isOwner}}
            <span><i class="fa fa-close"></i></span>
    {{else}}
        <span><i class="fa fa-bolt"></i></span>
        {{/if}}
        </span>
        <strong>{{userName}}:&nbsp;</strong>{{text}}
</div>
```

**Comment by bitwiseman** [comment] 2015-02-11 23:43
I marked this as a bug already.  The behavior is obviously wrong, and should be fixed. 

Are you trying to say that the issue you're seeing is caused by the "unformatted" setting?

**Comment by boustanihani** [comment] 2015-02-11 23:46
I'm not sure, just trying to understand the real issue & maybe find a temporary workaround :)

**Comment by MacKLess** [comment] 2018-07-25 19:36
This appears to have been fixed: 

{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_handlebars": true
}

**Closed** 2018-08-03 07:06 UTC
Labels: resolved: fixed?, type: bug
