### ISSUE TITLE
Span tags do not re-indent correctly

### ISSUE THREAD

**Issue by aeschli** [beautify-web/js-beautify#1010] opened 2016-08-30 06:47 UTC
_From @hhubik on August 28, 2016 20:37_
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:
1.  Open the test file in the attached [zip archive](https://github.com/Microsoft/vscode/files/441345/test.zip) in VS Code.
2. Execute "Formate Code" command (Alt-Shift-F).
3. Lines 68 and 79 are **not** properly indented as shown in this snapshot ![snapshot](https://cloud.githubusercontent.com/assets/14813201/18036602/08b98b70-6d3d-11e6-9b77-0cd0a4297b09.png)

_Copied from original issue: Microsoft/vscode#11069_

**Comment by aeschli** [comment] 2016-08-30 06:47
We're using the html beautifier from beautify-web/js-beautify.
Trying the example on http://jsbeautifier.org/ shows that the issue is with formatter.

**Comment by bitwiseman** [comment] 2016-08-30 18:02
Can you provide a more compact repro input?

**Comment by hhubik** [comment] 2016-08-30 18:12
@bitwiseman - I am afraid not.  The formatting works for me most of the time.  It only fails for me with this particular template file.  It could even be that the problem has something to do with the input **not being compact**.

**Comment by bitwiseman** [comment] 2016-08-31 23:03
As noted, this is an Angular 2 template file, not valid html , so that could be part of the problem.  If you trip out the Angular thing improve.

But It looks like main issue is with the span tags.  This input also repro's the problem:
```html
<div class="ui-grid-row ">
    <div class="ui-grid-col-12">
        <p-editor formControlName="voteDescriptionControl" [style]="{'height':'320px'}">
            <header>
                <span class="ql-formats">
                            <select class="ql-header">
                                <option selected></option>
                                <option value="1"></option>
                                <option value="2"></option>
                                <option value="3"></option>
                            </select>
                        </span>
                <span class="ql-formats">
        <button class="ql-bold"></button>
                            <button class="ql-italic"></button>
                            <button class="ql-underline"></button>
                                  <button class="ql-strike"></button>
                        </span>
                <span class="ql-formats"> 
                            <button class="ql-list" value="ordered"></button> 
                            <button class="ql-list" value="bullet"></button> 
                        </span>
                <span class="ql-formats"> 
                     <select class="ql-align"> 
 <option selected></option> 
                         <option value="center"></option> 
                         <option value="right"></option> 
                         <option value="justify"></option> 
                     </select> 
                 </span>
            </header>
        </p-editor>
    </div>
</div>
```

If you replace the `<span>`s with `<div>`s things get better but the `<select>` tags also seem to repro:
```html
<div class="ui-grid-row ">
    <div class="ui-grid-col-12">
        <p-editor formControlName="voteDescriptionControl" [style]="{'height':'320px'}">
            <header>
                <div class="ql-formats">
                    <select class="ql-header">
                                <option selected></option>
                                <option value="1"></option>
                                <option value="2"></option>
                                <option value="3"></option>
                            </select>
                </div>
                <div class="ql-formats">
                    <button class="ql-bold"></button>
                    <button class="ql-italic"></button>
                    <button class="ql-underline"></button>
                    <button class="ql-strike"></button>
                </div>
                <div class="ql-formats">
                    <button class="ql-list" value="ordered"></button>
                    <button class="ql-list" value="bullet"></button>
                </div>
                <div class="ql-formats">
                    <select class="ql-align"> 
 <option selected></option> 
                         <option value="center"></option> 
                         <option value="right"></option> 
                         <option value="justify"></option> 
                     </select>
                </div>
            </header>
        </p-editor>
    </div>
</div>
```

**Comment by hhubik** [comment] 2016-09-02 14:22
I tested it too.  Replacing spans with divs is acceptable.  The template still works in Angular2.  Formatting of the select statement still does not work, even with divs.  So at least that should be fixed.

**Comment by hhubik** [comment] 2016-09-02 14:26
On a second thought though ... I do not expect beautify to validate my HTML.  I use other tools for that.  I just expect it to make my code read.  Given that, I think formatting of the original test data (with spans) should work as well.

**Comment by HookyQR** [comment] 2017-03-21 03:50
This is likely caused by the fact that `span` and `select` are in the default list for `"unformatted"`.

**Comment by hhubik** [comment] 2017-03-21 05:02
@HookyQR is that something I, as a Visual Studio Code user, can change?  If so, how? I'd be happy to try that.

**Comment by HookyQR** [comment] 2017-03-21 08:25
Yep, there sure is. You can edit `"html.format.unformatted"` in your settings. It should auto fill with the defaults when you add it. Then remove `span` and `select` and you're good to go.

**Comment by hhubik** [comment] 2017-03-21 17:40
Thanks, @HookyQR. Removing select and span from the `unformatted` list fixed the problem for me.

**Comment by Denis-Frolov** [comment] 2017-05-08 16:52
Thanks, @HookyQR. This sure is the way to go. Replacing spans with div whata stupid advice.

**Comment by andreshg112** [comment] 2017-05-24 01:54
I did:
`"html.format.contentUnformatted": "",
    "html.format.unformatted": "",`

Now all my tags are being well formatted.

**Comment by MacKLess** [comment] 2018-08-04 06:47
This appears to have been resolved (at least the bitewiseman input examples) in v1.8.0-rc4

Output for both examples: 
```
<div class="ui-grid-row ">
    <div class="ui-grid-col-12">
        <p-editor formControlName="voteDescriptionControl" [style]="{'height':'320px'}">
            <header>
                <div class="ql-formats">
                    <select class="ql-header">
                        <option selected></option>
                        <option value="1"></option>
                        <option value="2"></option>
                        <option value="3"></option>
                    </select>
                </div>
                <div class="ql-formats">
                    <button class="ql-bold"></button>
                    <button class="ql-italic"></button>
                    <button class="ql-underline"></button>
                    <button class="ql-strike"></button>
                </div>
                <div class="ql-formats">
                    <button class="ql-list" value="ordered"></button>
                    <button class="ql-list" value="bullet"></button>
                </div>
                <div class="ql-formats">
                    <select class="ql-align">
                        <option selected></option>
                        <option value="center"></option>
                        <option value="right"></option>
                        <option value="justify"></option>
                    </select>
                </div>
            </header>
        </p-editor>
    </div>
</div>
```
@andreshg112  Please take a look and verify on http://jsbeautifier.org/

**Closed** 2018-08-17 00:46 UTC
Labels: language: html, resolved: fixed?, type: bug
