### ISSUE TITLE
Disable template handling, "<%" breaks beautify

### ISSUE THREAD

**Issue by Rob--W** [beautify-web/js-beautify#1661] opened 2019-04-16 10:40 UTC
The patch to #1377 breaks beautification when `"<%"` is present.

Template handling should be optional and preferably off by default (maybe on by default for HTML, but definitely off by default for JS).

Test case:

1. Visit https://beautifier.io/ 
2. Input `"<%";if(0){}`

Expected:
```
"<%";
if (0) {}
```

Actual:
```
"<%";if(0){}
```
This even happens if I set the dropdown to "Beautify JavaScript" to force beautification as JS rather than autodetect.

**Comment by bitwiseman** [comment] 2019-04-16 20:04
Duplicate of #1647.

**Closed** 2019-04-17 03:43 UTC
Labels: resolved: duplicate
