### ISSUE TITLE
Objects being indented too far

### ISSUE THREAD

**Issue by kennethslee613** [beautify-web/js-beautify#1698] opened 2019-08-14 20:24 UTC
# Input
The code looked like this before beautification:
```
doSomething({
  "foo": "bar"
}).then(console.log).catch(console.error);
```

# Expected Output
The code should have looked like this after beautification:
```
doSomething({
  "foo": "bar"
})
  .then(console.log)
  .catch(console.error);
```

# Actual Output
The  code actually looked like this after beautification:
```
doSomething({
    "foo": "bar"
  })
  .then(console.log)
  .catch(console.error);
```

## Environment
OS: vscode in MacOS

## Settings
Example:
```json
{
    "indent_size": 2,
    "indent_char": " ",
    "indent_with_tabs": false,
    "editorconfig": false,
    "eol": "\n",
    "end_with_newline": false,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "space_in_empty_paren": false,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "space_after_named_function": false,
    "brace_style": "collapse",
    "unindent_chained_methods": false,
    "break_chained_methods": true,
    "keep_array_indentation": false,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "e4x": false,
    "comma_first": false,
    "operator_position": "before-newline",
    "indent_empty_lines": false,
    "templating": ["auto"]
}
```

It seems that the closing brace and parenthesis is aligning with the chained function calls since setting break_chained_methods to false and keeping the chained function on the same line as the closing brace and parenthesis doesn't indent the object. However, I would like the chained functions to be indented while keeping the object unindented.

**Comment by bitwiseman** [comment] 2019-08-21 20:58
Duplicate of #1651

**Closed by bitwiseman** 2019-08-21 20:58 UTC
Labels: resolved: duplicate
