### ISSUE TITLE
Breaks content by wrapping in <pre> block.

### ISSUE THREAD

**Issue by garretwilson** [beautify-web/js-beautify#830] opened 2015-12-13 17:13 UTC
js-beautify wraps lines inside a `<pre>` block. This 100% absolutely breaks my content and is a show-stopper. You cannot wrap lines inside a `<pre>` block, as this is **pre**formatted code.

**Comment by bitwiseman** [comment] 2015-12-13 23:49
Please provide example input, expected output and actual output.

**Comment by romanseidl** [comment] 2016-01-15 18:37
I have the exact same problem. 

If it helps here is an example:

<pre lang="en" id="CA-2f84ecfbb9cf82350e81d6c9b69a81553fddd81b" dir="ltr"><span class="line"><span id="line-1-12" class="anchor"></span><span class="ResWord">print</span> <span class="ResWord">dir</span>(<span class="ID">__builtins__</span>)                <span class="Comment"># Hilfe Funktionsauflistung</span></span>
<span class="line"><span id="line-2-6" class="anchor"></span><span class="ResWord">print</span> <span class="ResWord">dir</span>(<span class="ID">__builtins__</span>.<span class="ID">list</span>)           <span class="Comment"># alle Funktionen die unter "list" verfügbar sind</span></span>
<span class="line"><span id="line-3-6" class="anchor"></span><span class="ResWord">print</span> <span class="ResWord">dir</span>(<span class="ID">__builtins__</span>.<span class="ID">list</span>.<span class="ID">sort</span>)      <span class="Comment"># die Unterfunktion sort in list (sortiere Liste)</span></span>
<span class="line"><span id="line-4-5" class="anchor"></span><span class="ResWord">print</span> <span class="ID">__builtins__</span>.<span class="ID">list</span>.<span class="ID">sort</span>.<span class="ID">__doc__</span>   <span class="Comment"># __doc__ ist immer die Doku zur Funktion</span></span>
</pre>

**Comment by bitwiseman** [comment] 2016-01-15 19:57
Interesting.  When I paste this into http://jsbeautifier.org/, it doesn't repro.

**Comment by romanseidl** [comment] 2016-01-15 20:36
I am using atom and the atom beautify package. And I can reproduce it in atom.

They claimed it's because of beautify-js:
https://github.com/Glavin001/atom-beautify/issues/708

But it seems you have seen that already. In Atom I can reproduce the problem.

**Comment by romanseidl** [comment] 2016-01-15 20:42
Thanks for the fast reply. Seems you can close this for js-beautify?

**Comment by bitwiseman** [comment] 2016-01-15 20:46
I'll leave it open until the other issue is closed.

**Closed** 2016-01-20 22:56 UTC
Labels: needs more info
