### ISSUE TITLE
cannot get space before function paren in es6 class.

### ISSUE THREAD

**Issue by zhangrunhao** [beautify-web/js-beautify#1665] opened 2019-04-23 10:21 UTC
# Description
> This is the default template for bug reports
>
> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue. 

# Input
The code looked like this before beautification:
```
export default class Test {
  constructor() {
    this.name = 'zhangrh'
  }
  tellName() {
    console.log(this.name)
  }
};

```

# Expected Output
The code should have looked like this after beautification:
```
export default class Test {
  constructor () {
    this.name = 'zhangrh'
  }
  tellName () {
    console.log(this.name)
  }
};
```

# Actual Output
The  code actually looked like this after beautification:
```
export default class Test {
  constructor() {
    this.name = 'zhangrh'
  }
  tellName() {
    console.log(this.name)
  }
};
```

# Steps to Reproduce

## Environment
OS:VSCode 1.33.1
js-beautify: 1.9.0

## Settings
Example:
```json
{
  "indent_size": 2,
  "js": {
    "space_after_anon_function": true,
    "space_after_named_function": true,
    "end_with_newline": true
  }
}
```

**Comment by bitwiseman** [comment] 2019-04-23 14:22
Please replace image with standard issue template - input, expected output, actual output.

**Comment by zhangrunhao** [comment] 2019-04-24 03:39
> Please replace image with standard issue template - input, expected output, actual output.

Hi, I have completed the change as required.

**Comment by bitwiseman** [comment] 2019-04-24 07:22
Thanks, now that I can see it, this is a duplicate of #1622.

**Closed** 2019-04-24 07:23 UTC
Labels: resolved: duplicate

**Comment by zhangrunhao** [comment] 2019-04-24 08:15
OK, I'll subscribe to another issue.
