### ISSUE TITLE
Spaces between function name an parenthesis

### ISSUE THREAD

**Issue by johannes-z** [beautify-web/js-beautify#727] opened 2015-06-26 19:19 UTC
It would be great if there was an option for the standard as defined here:
https://github.com/feross/standard#rules 
**Space after function name** `function name (arg) { ... }`
This already exists for anonymous functions, see: https://github.com/beautify-web/js-beautify/issues/372

**Comment by kirkstrobeck** [comment] 2015-07-23 18:41
+1

**Comment by bitwiseman** [comment] 2015-11-17 01:29
Duplicate of #608

**Closed** 2015-11-17 01:29 UTC
Labels: duplicate

**Comment by thurt** [comment] 2016-01-16 20:42
Depending on your environment, a possible alternative is to use their cli [standard-format](https://github.com/maxogden/standard-format). It looks like it currently has plugins for Ace and Sublime.
