### ISSUE TITLE
When prettifing css it adds new lines above all comments each time css it's prettified 

### ISSUE THREAD

**Issue by inflonet** [beautify-web/js-beautify#1219] opened 2017-07-19 15:15 UTC
# Description
I was pointed here to report this issue.
It happens in Sublime 3 while using Sublime-HTMLPrettify

Every time a css file it's prettified a new line it's added above comments. Exception is made for commented css rules and if there is a comment on the first line in the file. So if you prettify a css file 5 times you end up with 5 line breaks above each comment in the file.

This happened after the plugin was updated to 2.0.10 
https://github.com/victorporof/Sublime-HTMLPrettify/issues/451

# Input
The code looked like this before beautification:
```
/*----------------------someCss------------------------*/


.someCss {
         padding-top: 5px;
           padding-left: 5px;
    display: inline-block;
    /*padding-bottom: 0px;*/
}

/*----------------------anotherCss------------------------*/

         .anotherCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    padding-bottom: 0px;
}

```

# Expected Output
The code should have looked like this after 5 beautifications:
```
/*----------------------someCss------------------------*/

.someCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    /*padding-bottom: 0px;*/
}

/*----------------------anotherCss------------------------*/

.anotherCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    padding-bottom: 0px;
}

```

# Actual Output
The  code actually looked like this after 5 beautifications:
```
/*----------------------someCss------------------------*/

.someCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    /*padding-bottom: 0px;*/
}





*5 more lines above this comment
/*----------------------anotherCss------------------------*/

.anotherCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    padding-bottom: 0px;
}

```

# Steps to Reproduce

## Environment
OS: Max OS/Windows 10

## Settings
Tried all kinds of settings combination but nothing solved it.
Example:
```json
{
    "all":
    {
        "end_with_newline": false,
        "eol": "\n",
        "indent_level": 0,
        "indent_char": " ",
        "indent_size": 4,
        "indent_with_tabs": false,
        "max_preserve_newlines": 0,
        "preserve_newlines": true,
        "wrap_line_length": 0
    },
    "html":
    {
        "indent_handlebars": false,
        "indent_inner_html": false,          
        "indent_scripts": "keep",
        "unformatted": ["a", "span", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"]
    },

    "css":
    {
        "newline_between_rules": true,
        "selector_separator": " ",
        "selector_separator_newline": true
    },

    "js":
    {
        "brace_style": "collapse-preserve-inline",
        "break_chained_methods": false,
        "comma_first": false,
        "e4x": false,
        "jslint_happy": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "operator_position": "before-newline",
        "space_after_anon_function": false,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false
    },

    "json":
    {
        "brace_style": "expand",
        "keep_array_indentation": false,
        "unescape_strings": false
    },

    "custom":
    {
        {
            "indent_size": 2,
            "brace_style": "collapse"
        },

        "*.sublime-@(settings|keymap|commands|menu)":
        {
            "indent_size": 4,
            "brace_style": "expand"
        }
    }
}
```

**Comment by bitwiseman** [comment] 2017-07-25 19:54
Thank you for the detailed report.  This is a duplicate of #1185.

**Closed by bitwiseman** 2017-07-25 19:54 UTC
