### ISSUE TITLE
Optional chaining obj?.[expr]

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1801] opened 2020-05-18 08:17 UTC
The **`obj?.[expr]`** syntax of [optional chaining] don't work as expected:

# Input

  ```
  let nestedProp = obj?.['prop' + 'Name'];
  let arrayItem = arr?.[42];
  ```

# Expected (no change)

  ```
  let nestedProp = obj?.['prop' + 'Name'];
  let arrayItem = arr?.[42];
  ```

# Actual

  Space between `.` and `[`

  ```
  let nestedProp = obj?. ['prop' + 'Name'];
  let arrayItem = arr?. [42];
  ```

[Optional chaining]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Syntax

**Comment by bitwiseman** [comment] 2020-05-18 22:21
@laggingreflex  
These are equivalent to: 

```
let nestedProp = obj === null ?  null :  obj['prop' + 'Name'];
let arrayItem = arr === null ?  null :  ar[42];
```

Correct?

**Comment by laggingreflex** [comment] 2020-05-19 10:11
> These are equivalent to:    
>```js
>let nestedProp = (obj === null || obj === undefined) ?  null :  obj['prop' + 'Name'];
>let arrayItem = (arr === null || arr === undefined) ?  null :  arr[42];
>```


@bitwiseman Not sure I understand the question. Are you asking what the optional chaining operator `?.` expands to? Like as if it were parsed by Babel? [Babel expands it to this](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAdiDOYgCYAUBOB7ADhAvBdARgFYD8AdBANoDkmGm1EA1BNQHICGAtiNQLoBuAFChIHVKg4BPAJIIuuCONTkqAFgBMgoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose%2Ctypescript%2Cflow&prettier=false&targets=&version=7.9.6&externalPlugins=):

```js
var _obj, _arr;

var nestedProp = (_obj = obj) === null || _obj === void 0 ? void 0 : _obj['prop' + 'Name'];
var arrayItem = (_arr = arr) === null || _arr === void 0 ? void 0 : _arr[42];
```



> Also, these do not cause syntax errors, they just look wrong. Correct?

Yes, they don't cause any errors, just look wrong.

**Comment by bitwiseman** [comment] 2020-05-21 17:37
@laggingreflex 
I'm trying to understand the behavior of the language feature and the severity of the formatting problem.  

I don't have time to work on this right now, but the change should be pretty easy.  

Adding another branch to this conditional is prably the right place: 
https://github.com/beautify-web/js-beautify/blob/e4f9763c69ba8cf2a2fb1f10f19ef9d9611d1892/js/src/javascript/beautifier.js#L1260-L1273

**Comment by bitwiseman** [comment] 2020-08-04 20:10
Doh, this was a duplicate of #1727 which as fixed by #1779.  Fix released in 1.11.0.

**Comment by h0rn3z0r** [comment] 2021-01-26 12:42
@bitwiseman 
This issue is not fixed. The latest js-beautify still inserts an extra space character after the optional chaining operator.

**Comment by bitwiseman** [comment] 2021-01-26 17:05
@h0rn3z0r 
Hm, tests:
https://github.com/beautify-web/js-beautify/blob/4738a1dc43f95e92190d341aae8e310075a7074a/test/data/javascript/tests.js#L1054-L1075

Ah, I see the problem.

**Closed** 2021-01-26 17:32 UTC
Labels: good first issue, language: javascript, type: bug
